/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.40.2832
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.FeedbacksubmitData = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FeedbacksubmitData model module.
   * @module model/FeedbacksubmitData
   * @version 9.0.000.40.2832
   */

  /**
   * Constructs a new <code>FeedbacksubmitData</code>.
   * @alias module:model/FeedbacksubmitData
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FeedbacksubmitData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeedbacksubmitData} obj Optional instance to populate.
   * @return {module:model/FeedbacksubmitData} The populated <code>FeedbacksubmitData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('topic')) {
        obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
      }
      if (data.hasOwnProperty('settings')) {
        obj['settings'] = ApiClient.convertToType(data['settings'], Object);
      }
    }
    return obj;
  }

  /**
   * topic of feedback
   * @member {String} topic
   */
  exports.prototype['topic'] = undefined;
  /**
   * text of feedback
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * metadata of feedback
   * @member {String} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * setting of the record
   * @member {Object} settings
   */
  exports.prototype['settings'] = undefined;



  return exports;
}));


