/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.97.4639
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.MediaactivateData = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MediaactivateData model module.
   * @module model/MediaactivateData
   * @version 9.0.000.97.4639
   */

  /**
   * Constructs a new <code>MediaactivateData</code>.
   * @alias module:model/MediaactivateData
   * @class
   * @param channels {Array.<String>} An array of strings that correspond to the channels you want to activate.
   */
  var exports = function(channels) {
    var _this = this;


    _this['channels'] = channels;
  };

  /**
   * Constructs a <code>MediaactivateData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaactivateData} obj Optional instance to populate.
   * @return {module:model/MediaactivateData} The populated <code>MediaactivateData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('placeName')) {
        obj['placeName'] = ApiClient.convertToType(data['placeName'], 'String');
      }
      if (data.hasOwnProperty('channels')) {
        obj['channels'] = ApiClient.convertToType(data['channels'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The name of the place to use for the agent. You must provide either the place name.
   * @member {String} placeName
   */
  exports.prototype['placeName'] = undefined;
  /**
   * An array of strings that correspond to the channels you want to activate.
   * @member {Array.<String>} channels
   */
  exports.prototype['channels'] = undefined;



  return exports;
}));


