/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.61.3296
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.MediamediatypeinteractionsidconsultbyqueueData = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MediamediatypeinteractionsidconsultbyqueueData model module.
   * @module model/MediamediatypeinteractionsidconsultbyqueueData
   * @version 9.0.000.61.3296
   */

  /**
   * Constructs a new <code>MediamediatypeinteractionsidconsultbyqueueData</code>.
   * @alias module:model/MediamediatypeinteractionsidconsultbyqueueData
   * @class
   * @param queue {String} The name of the queue where the Workspace API should send the consult invite.
   */
  var exports = function(queue) {
    var _this = this;

    _this['queue'] = queue;
  };

  /**
   * Constructs a <code>MediamediatypeinteractionsidconsultbyqueueData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediamediatypeinteractionsidconsultbyqueueData} obj Optional instance to populate.
   * @return {module:model/MediamediatypeinteractionsidconsultbyqueueData} The populated <code>MediamediatypeinteractionsidconsultbyqueueData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('queue')) {
        obj['queue'] = ApiClient.convertToType(data['queue'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the queue where the Workspace API should send the consult invite.
   * @member {String} queue
   */
  exports.prototype['queue'] = undefined;



  return exports;
}));


