/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.23.2279
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.SupervisorvoiceoperationNameData = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SupervisorvoiceoperationNameData model module.
   * @module model/SupervisorvoiceoperationNameData
   * @version 9.0.000.23.2279
   */

  /**
   * Constructs a new <code>SupervisorvoiceoperationNameData</code>.
   * @alias module:model/SupervisorvoiceoperationNameData
   * @class
   * @param userName {String} userName of the user to logout
   * @param dn {String} DN of the user to logout
   */
  var exports = function(userName, dn) {
    var _this = this;

    _this['userName'] = userName;
    _this['dn'] = dn;
  };

  /**
   * Constructs a <code>SupervisorvoiceoperationNameData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SupervisorvoiceoperationNameData} obj Optional instance to populate.
   * @return {module:model/SupervisorvoiceoperationNameData} The populated <code>SupervisorvoiceoperationNameData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
      if (data.hasOwnProperty('dn')) {
        obj['dn'] = ApiClient.convertToType(data['dn'], 'String');
      }
    }
    return obj;
  }

  /**
   * userName of the user to logout
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;
  /**
   * DN of the user to logout
   * @member {String} dn
   */
  exports.prototype['dn'] = undefined;



  return exports;
}));


