/**
 * Workspace API
 * Application API used by Workspace Web Edition
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.CurrentUserDataPendingloginasync = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CurrentUserDataPendingloginasync model module.
   * @module model/CurrentUserDataPendingloginasync
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CurrentUserDataPendingloginasync</code>.
   * @alias module:model/CurrentUserDataPendingloginasync
   * @class
   * @param state {module:model/CurrentUserDataPendingloginasync.StateEnum} 
   * @param actualWaitTime {Number} 
   * @param submittedAt {String} 
   */
  var exports = function(state, actualWaitTime, submittedAt) {
    var _this = this;

    _this['state'] = state;
    _this['actualWaitTime'] = actualWaitTime;
    _this['submittedAt'] = submittedAt;

  };

  /**
   * Constructs a <code>CurrentUserDataPendingloginasync</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrentUserDataPendingloginasync} obj Optional instance to populate.
   * @return {module:model/CurrentUserDataPendingloginasync} The populated <code>CurrentUserDataPendingloginasync</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('actualWaitTime')) {
        obj['actualWaitTime'] = ApiClient.convertToType(data['actualWaitTime'], 'Number');
      }
      if (data.hasOwnProperty('submittedAt')) {
        obj['submittedAt'] = ApiClient.convertToType(data['submittedAt'], 'String');
      }
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CurrentUserDataPendingloginasync.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Number} actualWaitTime
   */
  exports.prototype['actualWaitTime'] = undefined;
  /**
   * @member {String} submittedAt
   */
  exports.prototype['submittedAt'] = undefined;
  /**
   * @member {Object} errors
   */
  exports.prototype['errors'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "NotStarted"
     * @const
     */
    "NotStarted": "NotStarted",
    /**
     * value: "Executing"
     * @const
     */
    "Executing": "Executing",
    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",
    /**
     * value: "Complete"
     * @const
     */
    "Complete": "Complete"  };


  return exports;
}));


