/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.NotificationsApi = factory(root.WorkspaceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Notifications service.
   * @module api/NotificationsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new NotificationsApi. 
   * @alias module:api/NotificationsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Enables subscription to CometD notification API
     * Receives one of CometD notification events The following events are available &lt;h3&gt;/workspace/v3/initialization&lt;/h3&gt; Field &lt;b&gt;data.state&lt;/b&gt; Value   \&quot;Complete\&quot; Initialization was completed successfully   \&quot;Failed\&quot;   Initialization failed &lt;h3&gt;/workspace/v3/voice&lt;/h3&gt; Field &lt;b&gt;data.messageType&lt;/b&gt; Value   \&quot;CallStateChanged\&quot;  Call status or state changed   \&quot;DnStateChanged\&quot;    DN state changed   \&quot;EventError\&quot;        Error occured &lt;h3&gt;CallStateChanged&lt;/h3&gt; Field &lt;b&gt;data.call.stat&lt;/b&gt; Value   \&quot;Ringing\&quot;   Ringing in progressl   \&quot;Dialing\&quot;   Dialing in progress   \&quot;Released\&quot;  Call released &lt;h3&gt;DnStateChanged&lt;/h3&gt; Field &lt;b&gt;data.dn&lt;/b&gt; Value   message   DN state changed 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Enables subscription to CometD notification API
     * Receives one of CometD notification events The following events are available &lt;h3&gt;/workspace/v3/initialization&lt;/h3&gt; Field &lt;b&gt;data.state&lt;/b&gt; Value   \&quot;Complete\&quot; Initialization was completed successfully   \&quot;Failed\&quot;   Initialization failed &lt;h3&gt;/workspace/v3/voice&lt;/h3&gt; Field &lt;b&gt;data.messageType&lt;/b&gt; Value   \&quot;CallStateChanged\&quot;  Call status or state changed   \&quot;DnStateChanged\&quot;    DN state changed   \&quot;EventError\&quot;        Error occured &lt;h3&gt;CallStateChanged&lt;/h3&gt; Field &lt;b&gt;data.call.stat&lt;/b&gt; Value   \&quot;Ringing\&quot;   Ringing in progressl   \&quot;Dialing\&quot;   Dialing in progress   \&quot;Released\&quot;  Call released &lt;h3&gt;DnStateChanged&lt;/h3&gt; Field &lt;b&gt;data.dn&lt;/b&gt; Value   message   DN state changed 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notifications = function() {
      return this.notificationsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Subscribes to CometD notifications
     * Subscribes to CometD notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsConnectWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications/connect', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Subscribes to CometD notifications
     * Subscribes to CometD notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notificationsConnect = function() {
      return this.notificationsConnectWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Close CometD notification subscriptions
     * Close CometD notification subscriptions
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsDisconnectWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications/disconnect', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Close CometD notification subscriptions
     * Close CometD notification subscriptions
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notificationsDisconnect = function() {
      return this.notificationsDisconnectWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Subscribes to CometD notifications
     * Subscribes to CometD notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsHandshakeWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications/handshake', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Subscribes to CometD notifications
     * Subscribes to CometD notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notificationsHandshake = function() {
      return this.notificationsHandshakeWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Subscribes CometD channel notification
     * Subscribes CometD channel notification. The following channels are available right now&lt;br&gt;  &lt;b&gt;/workspace/v3/initialization&lt;/b&gt; Subscribe for initialization (login) event &lt;b&gt;/workspace/v3/voice&lt;/b&gt; Subscribe for call state change notification event 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsSubscribeWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications/subscribe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Subscribes CometD channel notification
     * Subscribes CometD channel notification. The following channels are available right now&lt;br&gt;  &lt;b&gt;/workspace/v3/initialization&lt;/b&gt; Subscribe for initialization (login) event &lt;b&gt;/workspace/v3/voice&lt;/b&gt; Subscribe for call state change notification event 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notificationsSubscribe = function() {
      return this.notificationsSubscribeWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Unsubscribes CometD channel notification
     * Unsubscribes CometD channel notification
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.notificationsUnsubscribeWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/notifications/unsubscribe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Unsubscribes CometD channel notification
     * Unsubscribes CometD channel notification
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.notificationsUnsubscribe = function() {
      return this.notificationsUnsubscribeWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Enables subscription to SocketIO notifications
     * Enables subscription to SocketIO notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.socketioWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/socket.io', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Enables subscription to SocketIO notifications
     * Enables subscription to SocketIO notifications
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.socketio = function() {
      return this.socketioWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
