/**
 * Workspace API
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.33.2671
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiErrorResponse', 'model/ApiSuccessResponse', 'model/SupervisorPlaceData', 'model/SupervisorPlaceData1'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiErrorResponse'), require('../model/ApiSuccessResponse'), require('../model/SupervisorPlaceData'), require('../model/SupervisorPlaceData1'));
  } else {
    // Browser globals (root is window)
    if (!root.WorkspaceApi) {
      root.WorkspaceApi = {};
    }
    root.WorkspaceApi.UsersApi = factory(root.WorkspaceApi.ApiClient, root.WorkspaceApi.ApiErrorResponse, root.WorkspaceApi.ApiSuccessResponse, root.WorkspaceApi.SupervisorPlaceData, root.WorkspaceApi.SupervisorPlaceData1);
  }
}(this, function(ApiClient, ApiErrorResponse, ApiSuccessResponse, SupervisorPlaceData, SupervisorPlaceData1) {
  'use strict';

  /**
   * Users service.
   * @module api/UsersApi
   * @version 9.0.000.33.2671
   */

  /**
   * Constructs a new UsersApi. 
   * @alias module:api/UsersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Search for users.
     * Search for users with the specified filters.
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchTerm The text to search.
     * @param {Number} opts.groupId The ID of the group where the user belongs.
     * @param {String} opts.sort The sort order, either &#x60;asc&#x60; (ascending) or &#x60;desc&#x60; (descending). The default is &#x60;asc&#x60;.
     * @param {Number} opts.limit Number of results to return. The default value is 100.
     * @param {Number} opts.offset The offset to start from in the results. The default value is 0.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiSuccessResponse} and HTTP response
     */
    this.getUsersWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'searchTerm': opts['searchTerm'],
        'groupId': opts['groupId'],
        'sort': opts['sort'],
        'limit': opts['limit'],
        'offset': opts['offset'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ApiSuccessResponse;

      return this.apiClient.callApi(
        '/users', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Search for users.
     * Search for users with the specified filters.
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchTerm The text to search.
     * @param {Number} opts.groupId The ID of the group where the user belongs.
     * @param {String} opts.sort The sort order, either &#x60;asc&#x60; (ascending) or &#x60;desc&#x60; (descending). The default is &#x60;asc&#x60;.
     * @param {Number} opts.limit Number of results to return. The default value is 100.
     * @param {Number} opts.offset The offset to start from in the results. The default value is 0.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiSuccessResponse}
     */
    this.getUsers = function(opts) {
      return this.getUsersWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Change the state of the agent specified by the dbid to operationName.
     * Change the state of the agent specified by the dbid to operationName.
     * @param {String} dbid The dbid of the agent.
     * @param {String} mediatype The media channel.
     * @param {module:model/String} operationName Name of state to change to
     * @param {Object} opts Optional parameters
     * @param {module:model/SupervisorPlaceData1} opts.supervisorPlaceData Request parameters.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiSuccessResponse} and HTTP response
     */
    this.supervisorRemoteMediaOperationWithHttpInfo = function(dbid, mediatype, operationName, opts) {
      opts = opts || {};
      var postBody = opts['supervisorPlaceData'];

      // verify the required parameter 'dbid' is set
      if (dbid === undefined || dbid === null) {
        throw new Error("Missing the required parameter 'dbid' when calling supervisorRemoteMediaOperation");
      }

      // verify the required parameter 'mediatype' is set
      if (mediatype === undefined || mediatype === null) {
        throw new Error("Missing the required parameter 'mediatype' when calling supervisorRemoteMediaOperation");
      }

      // verify the required parameter 'operationName' is set
      if (operationName === undefined || operationName === null) {
        throw new Error("Missing the required parameter 'operationName' when calling supervisorRemoteMediaOperation");
      }


      var pathParams = {
        'dbid': dbid,
        'mediatype': mediatype,
        'operationName': operationName
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ApiSuccessResponse;

      return this.apiClient.callApi(
        '/users/{dbid}/media/{mediatype}/{operationName}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Change the state of the agent specified by the dbid to operationName.
     * Change the state of the agent specified by the dbid to operationName.
     * @param {String} dbid The dbid of the agent.
     * @param {String} mediatype The media channel.
     * @param {module:model/String} operationName Name of state to change to
     * @param {Object} opts Optional parameters
     * @param {module:model/SupervisorPlaceData1} opts.supervisorPlaceData Request parameters.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiSuccessResponse}
     */
    this.supervisorRemoteMediaOperation = function(dbid, mediatype, operationName, opts) {
      return this.supervisorRemoteMediaOperationWithHttpInfo(dbid, mediatype, operationName, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Logout user remotely for supervisors
     * @param {module:model/String} operationName Name of state to change to
     * @param {String} dbid The dbid of the agent.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiSuccessResponse} and HTTP response
     */
    this.supervisorRemoteOperationWithHttpInfo = function(operationName, dbid) {
      var postBody = null;

      // verify the required parameter 'operationName' is set
      if (operationName === undefined || operationName === null) {
        throw new Error("Missing the required parameter 'operationName' when calling supervisorRemoteOperation");
      }

      // verify the required parameter 'dbid' is set
      if (dbid === undefined || dbid === null) {
        throw new Error("Missing the required parameter 'dbid' when calling supervisorRemoteOperation");
      }


      var pathParams = {
        'operationName': operationName,
        'dbid': dbid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ApiSuccessResponse;

      return this.apiClient.callApi(
        '/users/{dbid}/voice/{operationName}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Logout user remotely for supervisors
     * @param {module:model/String} operationName Name of state to change to
     * @param {String} dbid The dbid of the agent.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiSuccessResponse}
     */
    this.supervisorRemoteOperation = function(operationName, dbid) {
      return this.supervisorRemoteOperationWithHttpInfo(operationName, dbid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Change the state of the agent specified by the dbid to operationName.
     * Change the state of the agent specified by the dbid to operationName.
     * @param {String} dbid The dbid of the agent.
     * @param {Object} opts Optional parameters
     * @param {module:model/SupervisorPlaceData} opts.supervisorPlaceData Request parameters.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiSuccessResponse} and HTTP response
     */
    this.supervisorRemotePlaceOperationWithHttpInfo = function(dbid, opts) {
      opts = opts || {};
      var postBody = opts['supervisorPlaceData'];

      // verify the required parameter 'dbid' is set
      if (dbid === undefined || dbid === null) {
        throw new Error("Missing the required parameter 'dbid' when calling supervisorRemotePlaceOperation");
      }


      var pathParams = {
        'dbid': dbid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ApiSuccessResponse;

      return this.apiClient.callApi(
        '/users/{dbid}/media/logout', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Change the state of the agent specified by the dbid to operationName.
     * Change the state of the agent specified by the dbid to operationName.
     * @param {String} dbid The dbid of the agent.
     * @param {Object} opts Optional parameters
     * @param {module:model/SupervisorPlaceData} opts.supervisorPlaceData Request parameters.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiSuccessResponse}
     */
    this.supervisorRemotePlaceOperation = function(dbid, opts) {
      return this.supervisorRemotePlaceOperationWithHttpInfo(dbid, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
